# Generated by Django 2.2.5 on 2020-07-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='zip',
        ),
    ]
